GET http://localhost:8082/provider/thread

###

GET http://localhost:8082/provider/echo/66567890

###

GET http://localhost:9000/nacos/kobe/provider/echo/kkkkkkkkkkk
X-Request-Id: 23244567

###

GET http://localhost:9000/nacos/kobe/provider/echo/kkkkkkkkkkk
tokenid: 1

###
